const myList = [
    "Owie owie it burns help me ouuuu owww", 
    "What a terrible day to have fingers to type with", 
    "Up at 4 in the morning, doing god knows what.", 
    "What are you looking for?", 
    "See if i only had drilly fingers i would've crawled through this already",
    "Hurt, suffering, pineapples.",
    "Lets see how many references i can make out of this albums' songs",
    "1. Let me change the past by what i now am",
    "2. A fucking disgrace, haha.",
    "3. How are you walking that way away",
    "4. Oh my fucking god.",
    "5. And yet you all continue walking to obscure us",
    "6. Pirates! Pirates! Yarghhh!",
    "7. It won't be worth it.",
    "8. Go on now, move forward, cycle of heckin' life, kids.",
    "9. LET THERE BE MEANING AS WE WILL IT",
    "10. blablablablablabalablabla",
    "11. 50 stacks of bricks, on my face, laced with dynamite, fix the shite i graced: action.",
    "12. Can't stop it.",
    "13. It's nothing personal, i'll have you know, it's simply how life goes.",
    "14. Sandpapering your teeth to smile better",
    "15. what you did, have it at you",
    "16. weehoo, waahoo, YEAOUGH.",
    "17. Lacking hope can't be motivational, surely",
    "18. Lets be cute, hey??? How's your life?",
    "19. do drugs kids Don't, ",
    "20. AAAAAAAARGHHHHHH YEAHHHHHHHHHHHHHHHH",
    "21. AAGHHHHH NOOOOOOOOOOO CMOOOOOOOOOOOOOOON",
    "22. ................................",
    "23. ah, what to do?",
    "24. lost love systematically",
    "25. Go fuck yourself, honestly, scumbag.",
    "26. We've exhausted what's in the past to return for",
    "27. I'll never die you bitches",
    "28. I mean the title really says this one.",
    "29. i'm kinda done, y'know?",
    "30. still work to be done",
    "31. EPIC SAXOPHONE RIFF",
    "32. I've always been here, you just haven't noticed.",
    "33. Stick the landing and the kick to the head.",
    "34. I fondly remember how i started hurting, oh how i wish i couldn't."
];
randomizeFunction()
function randomizeFunction() {
    document.getElementById("randomWord").innerHTML = myList[Math.floor(Math.random() * myList.length)]
}